const KIND = {
    STABILITY: 'STABILITY',
    EXPERIENCE: 'EXPERIENCE',
    BUSINESS: 'BUSINESS'
};
const TYPE = {
    ERROR: 'ERROR',
    XHR: 'XHR',
    BLANK: 'BLANK',
    TIMING: 'TIMING',
    FIRST_INPUT_DELAY: 'FIRST_INPUT_DELAY',
    PAINT: 'PAINT',
    LONG_TASK: 'LONG_TASK',
    PV: 'PV',
    STAY_TIME: 'STAY_TIME'
};
const ERROR_TYPE = {
    JS: 'JS_ERROR',
    RESOURCE: 'RESOURCE_ERROR',
    PROMISE: 'PROMISE_ERROR',
    XHR: 'XHR'
};
export {
    KIND,
    TYPE,
    ERROR_TYPE
}